# Generated by Django 3.0.2 on 2020-01-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_name', models.TextField()),
                ('jobs_description', models.TextField()),
                ('jobs_Title', models.TextField()),
                ('location', models.TextField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
